apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-arena-auth-service-deployment
  labels:
    app: mi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-arena-auth-service
  template:
    metadata:
      labels:
        app: java-arena-auth-service
    spec:
      containers:
        - name: java-arena-auth-service-container
          image: gcr.io/tu-proyecto-id/java-arena-auth-service:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"