# service-account.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-kubernetes-sa
  namespace: default # Or your specific namespace where the deployment runs
  annotations:
    # This annotation maps the K8s Service Account to the GCP Service Account
    iam.gke.io/gcp-service-account: auth-service-cloudsql-sa@java-arena.iam.gserviceaccount.com