apiVersion: v1
kind: Service
metadata:
  name: java-arena-auth-service
spec:
  selector:
    app: java-arena-auth-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080